{{- if .Values.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "podinfo.fullname" . }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: ./{{ template "podinfo.fullname" . }}.rules
    rules:
    - alert: TooManyStoredFiles
      expr: stored_files > 5
{{- end }}